name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest  # Or your preferred runner OS
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
        
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./terraform"

      - name: 'Terraform Validate'  # Uncomment if needed
        uses: hashicorp/terraform-github-actions@master
        with:
        
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./terraform"

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-actions@master
        with:
        
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./terraform"
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Apply  # Add this step if needed, with appropriate conditions
        if: github.ref == 'refs/heads/main'  # Apply only on main branch pushes
        uses: hashicorp/terraform-github-actions@master
        with:
        
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./terraform"
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
