name: Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.8

      - name: Display Current Directory
        run: |
          pwd
          ls -l

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan
        env:
          TF_IN_AUTOMATION: "true"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform
        run: |
          terraform apply -auto-approve
        env:
          TF_IN_AUTOMATION: "true"
