name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List files in the terraform directory
        run: ls terraform

      - name: Change directory to Terraform directory
        run: cd terraform

      - name: Print current directory
        run: pwd



      - name: Configure Terraform
        run: |
          terraform init

      - name: Validate Terraform Configuration
        run: |
          terraform validate

        env:
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      
      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan
        env:
          TF_IN_AUTOMATION: "true"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -auto-approve
        env:
          TF_IN_AUTOMATION: "true"
