name: Deploy to Azure

on:
  push:
    branches: [ main ]  # Change to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: Azure/login@v1
        with:
          clientId: ${{ secrets.AZURE_CLIENT_ID }}
          
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Azure Provider (optional, if not using remote state)
        uses: HashiCorp/terraform-init@v1
        with:
          backend: false

      - name: Initialize Terraform
        uses: HashiCorp/terraform-init@v1

      - name: Plan Terraform changes (optional)
        run: terraform plan

      - name: Apply Terraform changes
        run: terraform apply -auto-approve

      - name: Optional: Destroy resources (for testing or cleanup)
        run: terraform destroy -auto-approve  # Uncomment for testing or cleanup
